### ISSUE TITLE
Would please tell me why it always tell me "out-of-memory"?

### ISSUE THREAD

**Issue by wangxiao5791509** [peizhaoli05/EDA_GNN#2]
![image](https://user-images.githubusercontent.com/12805786/61460163-89570d80-a9b1-11e9-9775-dd86562f0c72.png)

![image](https://user-images.githubusercontent.com/12805786/61460237-ae4b8080-a9b1-11e9-8afd-77d6f22ead1d.png)

As shown in above, would you please tell me which parameter should I tune to avoid this error?  I tried the length of history frame (5 -> 2), and also some other ways, but all failed. Thanks, bro.

**Comment by tranthanhsongitrepo** [comment]
To anyone who's trying to solve this, this is caused by the LoadImg function in Generator.py. Just use the original image instead of a copy
